clipboard_program wl-copy
shell fish
allow_remote_control yes
cursor_shape block
confirm_os_window_close 0
# copy to clipboard
map ctrl+c copy_to_clipboard

# paste from clipboard
map ctrl+v paste_from_clipboard

# auto-copy on selection
selection_to_clipboard yes



font_size 12.0
font_family JetBrainsMono Nerd Font
# font_size 14.0
# font_family CaskaydiaCove Nerd Font Mono


# BEGIN_KITTY_THEME
# Argonaut
include current-theme.conf
# END_KITTY_THEME

# Trail length (try from 1 to 10)
cursor_trail 3

# How fast the trail fades
cursor_trail_decay 0.1 0.4

# Initial trail thickness relative to cursor
cursor_trail_start_threshold 2

# Set opacity to 1.0 so Hyprland can lower it itself
background_opacity 0.8

